{{- if .Values.mariadb.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "teamspeak.mariadb.fullname" . }}-secret
  labels:
{{ include "teamspeak.labels" . | nindent 4 }}
type: Opaque
data:
  mysql-root-password: {{ .Values.mariadb.auth.rootPassword | b64enc | quote }}
  mysql-password: {{ .Values.mariadb.auth.password | b64enc | quote }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "teamspeak.fullname" . }}-config
  labels:
{{ include "teamspeak.labels" . | nindent 4 }}
type: Opaque
data:
  tsserver.yaml: {{ include "teamspeak.serverConfig" . | b64enc | quote }}
---
{{- if .Values.mariadb.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "teamspeak.mariadb.fullname" . }}-config
  labels:
{{ include "teamspeak.labels" . | nindent 4 }}
data:
  my.cnf: |-
{{ .Values.mariadb.primary.configuration | indent 4 }}
{{- end }}